[font]
size = 15.0

[font.bold]
family = "Geist Mono"
style = "Bold"

[font.bold_italic]
family = "Geist Mono"

[font.italic]
family = "Geist Mono"
style = "Italic"

[font.normal]
family = "Geist Mono"
style = "Regular"

[scrolling]
history = 20000

[window]
decorations = "Full"
dynamic_padding = false

[window.padding]
x = 0
y = 0

[terminal]
shell = "fish"

[selection]
save_to_clipboard = true

[general]
import = [ "~/.config/alacritty/themes/themes/autumn.toml" ]
