eval %sh{ kak-tree-sitter -dks --init $kak_session }
colorscheme everforest-dark-hard
eval %sh{ kak-lsp }
lsp-enable

map -docstring "next" global prompt "<c-n>" "<tab>"
map -docstring "prev" global prompt "<c-p>" "<s-tab>"

source "%val{config}/bundle/kak-bundle/rc/kak-bundle.kak"
bundle-noload kak-bundle https://codeberg.org/jdugan6240/kak-bundle

bundle parinfer-rust https://github.com/eraserhd/parinfer-rust %{
    hook global WinSetOption filetype=(clojure|lisp|racket|scheme) %{
        parinfer-enable-window -smart
    }
}
bundle-install-hook parinfer-rust %{
    cargo install --force --path .
}

bundle fzf-kak https://github.com/andreyorst/fzf.kak %{}
require-module fzf

define-command tmux-switch-pane %{nop %sh{
    tmux select-pane -t :.+
} }
map global normal <c-l> ':tmux-switch-pane<ret>'

define-command new-hsplit -docstring 'horizontal split' -params .. %{
    tmux-terminal-horizontal kak -c %val{session} -e "%arg{@}"
}
define-command new-vsplit -docstring 'vertical split' -params .. %{
    tmux-terminal-vertical kak -c %val{session} -e "%arg{@}"
}

declare-user-mode window
map global normal <c-w> ':enter-user-mode window<ret>'
map global window v ':new-hsplit<ret>'
map global window s ':new-vsplit<ret>'

declare-user-mode project
map global user p -docstring 'project management' ':enter-user-mode project<ret>'
map global project f -docstring 'find file' ':fzf -fzf-args "--exact" -kak-cmd "e" -items-cmd "fd --type file"<ret>'

map global user l -docstring 'lsp' ':enter-user-mode lsp<ret>'
