eval %sh{ kak-tree-sitter -dks --init $kak_session }

colorscheme everforest-dark-hard

eval %sh{ kak-lsp }
lsp-enable

map -docstring "next" global prompt "<c-n>" "<tab>"
map -docstring "prev" global prompt "<c-p>" "<s-tab>"

source "%val{config}/bundle/kak-bundle/rc/kak-bundle.kak"
bundle-noload kak-bundle https://codeberg.org/jdugan6240/kak-bundle

bundle parinfer-rust https://github.com/eraserhd/parinfer-rust %{
    hook global WinSetOption filetype=(clojure|lisp|racket|scheme) %{
        parinfer-enable-window -smart
    }
}
bundle-install-hook parinfer-rust %{
    cargo install --force --path .
}

define-command tmux-switch-pane %{nop %sh{
    tmux select-pane -t :.+
} }
map global normal <c-l> ': tmux-switch-pane<ret>'

define-command new-hsplit -docstring 'horizontal split' -params .. %{
    tmux-terminal-horizontal kak -c %val{session} -e "%arg{@}"
}
define-command new-vsplit -docstring 'vertical split' -params .. %{
    tmux-terminal-vertical kak -c %val{session} -e "%arg{@}"
}

declare-user-mode window
map global normal <c-w> ': enter-user-mode window<ret>'
map global window v ': new-hsplit<ret>'
map global window s ': new-vsplit<ret>'

map global user l -docstring 'lsp' ': enter-user-mode lsp<ret>'

hook global BufSetOption filetype=nix %{
    set buffer formatcmd 'nixfmt'
}
hook global BufWritePre .* %{
    evaluate-commands %sh{
        if [ -n "$kak_opt_formatcmd" ]; then
            echo format
        fi
    }
}

define-command tmuxv -hidden -params .. %{
    evaluate-commands %sh{
        tmux splitw -v -l 30% "$@"
    }
}

# Mappings
map global user b ': fzf-switch-buffer<ret>'

declare-user-mode project
map global project f -docstring 'find file' ': fzf-project-file<ret>'
map global user p -docstring 'project management' ': enter-user-mode project<ret>'
