#!/usr/bin/env bash

sxhkd &
#xkbcomp ~/dhm.xkb $DISPLAY &
polybar right &
polybar left &

bspc monitor DVI-I-1 -d 5 6 7 8
bspc monitor DVI-D-1 -d 1 2 3 4

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop --focus 1
