#!/nix/store/5hplxs3kprdp6v62qk3di6a1m1s1paiq-bash-4.4-p23/bin/sh

sxhkd &
xrandr --output DVI-D-1 --left-of DVI-I-1 & \
xkbcomp ~/dhm.xkb $DISPLAY &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
