#!/usr/bin/env bash

xrandr --output DP-2 --rate 72.01 --right-of HDMI-0 &
feh --bg-scale $HOME/purple_street.jpeg &
sxhkd &
polybar left &
polybar right &
xinput set-prop 'SYNA1202:00 06CB:CD64 Touchpad' 'libinput Natural Scrolling Enabled' 1 &
xinput set-prop 'SYNA1202:00 06CB:CD64 Touchpad' 'libinput Tapping Enabled' 1 &
xinput set-prop 'Logitech USB-PS/2 Optical Mouse' 'libinput Natural Scrolling Enabled' 1 &

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          22

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
