# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations
    abbr --add -- d 'cd ~/dotfiles'
    abbr --add -- dea 'direnv allow'
    abbr --add -- ded 'direnv deny'
    abbr --add -- der 'direnv reload'
    abbr --add -- doom '~/.config/emacs/bin/doom'
    abbr --add -- drun 'docker run -it --rm'
    abbr --add -- drunl 'docker run -it --rm --mount type=bind,source=$(pwd),target=/foo'
    abbr --add -- dsp 'docker system prune'
    abbr --add -- dual-monitor 'xrandr --output HDMI-0 --off && xrandr --auto && xrandr --output HDMI-0 --primary --output eDP-1-1 --mode 1920x1080 --right-of HDMI-0'
    abbr --add -- e 'emacsclient --alternate-editor '\'''\'' --create-frame --no-wait'
    abbr --add -- ec 'emacsclient --alternate-editor '\'''\'' --no-wait'
    abbr --add -- eg 'emacsclient --alternate-editor '\'''\'' --create-frame --eval '\''(magit-status)'\'''
    abbr --add -- ekill 'env -u ALTERNATE_EDITOR emacsclient --eval '\''(kill-emacs)'\'' 2>/dev/null'
    abbr --add -- et 'emacsclient --alternate-editor '\'''\'' --tty'
    abbr --add -- g git
    abbr --add -- ga 'git add'
    abbr --add -- gap 'git add -p'
    abbr --add -- gb 'git branch -v'
    abbr --add -- gc 'git commit -v'
    abbr --add -- gca 'git commit -v --amend'
    abbr --add -- gcl 'git clone'
    abbr --add -- gcm 'git commit -v -m'
    abbr --add -- gd 'git diff'
    abbr --add -- gds 'git diff --staged'
    abbr --add -- gf 'git fetch'
    abbr --add -- gfa 'git fetch --all'
    abbr --add -- gfu 'git fetch upstream'
    abbr --add -- gi 'git init'
    abbr --add -- gl 'git pull'
    abbr --add -- glo 'git log --oneline --decorate'
    abbr --add -- glog 'git log --oneline --decorate --graph'
    abbr --add -- gm 'git merge'
    abbr --add -- gp 'git push'
    abbr --add -- gpra 'git pull --rebase --autostash'
    abbr --add -- gpu 'git push --set-upstream origin'
    abbr --add -- gr 'git remote'
    abbr --add -- gra 'git remote add'
    abbr --add -- grb 'git rebase'
    abbr --add -- grs 'git restore'
    abbr --add -- grss 'git restore --staged'
    abbr --add -- grv 'git remote -v'
    abbr --add -- gs 'git status --short'
    abbr --add -- gst 'git status'
    abbr --add -- gsw 'git switch'
    abbr --add -- gw 'git worktree'
    abbr --add -- gwa 'git worktree add'
    abbr --add -- gwl 'git worktree list'
    abbr --add -- hs 'nix shell "$HOME/dotfiles/#nixosConfigurations.$(hostname).config.home-manager.users.$USER.home.activationPackage" --command home-manager-generation'
    abbr --add -- jo 'journalctl -u'
    abbr --add -- jou 'journalctl --user -u'
    abbr --add -- md 'mkdir -p'
    abbr --add -- n nix
    abbr --add -- nb 'nix build'
    abbr --add -- nd 'nix develop'
    abbr --add -- nf 'nix flake'
    abbr --add -- nfl 'nix flake lock'
    abbr --add -- nfu 'nix flake update'
    abbr --add -- nr 'nix run'
    abbr --add -- nrb 'nixos-rebuild boot --use-remote-sudo --flake ~/dotfiles/'
    abbr --add -- nrs 'nixos-rebuild switch --use-remote-sudo --flake ~/dotfiles/'
    abbr --add -- ns 'nix shell'
    abbr --add -- nsn 'nix search nixpkgs'
    abbr --add -- nst 'nix search this'
    abbr --add -- rr 'rm -rf'
    abbr --add -- s sudo
    abbr --add -- serve-this '/nix/store/8w718rm43x7z73xhw9d6vh8s4snrq67h-python3-3.12.10/bin/python3.12 -m http.server'
    abbr --add -- single-monitor 'xrandr --output HDMI-0 --off'
    abbr --add -- sy systemctl
    abbr --add -- syu 'systemctl --user'
    abbr --add -- v nvim

    # Aliases
    alias l 'eza -lbF --group-directories-first --icons'
    alias la 'eza -labF --group-directories-first --icons'
    alias ll 'eza -lbGF --group-directories-first --icons'
    alias lla 'eza -labGF --group-directories-first --icons'
    alias ls eza

    # Interactive shell initialisation
    set fish_greeting
    bind \cp navigate_to_project
    bind \cr command_history_search
    bind \cv open_file_in_emacs

    fish_add_path --path $HOME/.config/emacs/bin
    fish_add_path --path $HOME/.local/bin

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/void/.local/share/fish/home-manager_generated_completions" $post
    end

    direnv hook fish | source

end
