local result, treesitter_configs = pcall(require, "nvim-treesitter.configs")
if not result then
    return
end

treesitter_configs.setup {
    ensure_installed = {
        "awk",
        "bash",
        "c",
        "clojure",
        "cmake",
        "commonlisp",
        "cpp",
        "css",
        "dockerfile",
        "dot",
        "elixir",
        "elm",
        "erlang",
        "fennel",
        "fish",
        "gleam",
        "glsl",
        "go",
        "haskell",
        "html",
        "http",
        "java",
        "javascript",
        "jq",
        "json",
        "json5",
        "latex",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "mermaid",
        "nix",
        "ocaml",
        "ocaml_interface",
        "org",
        "perl",
        "proto",
        "python",
        "racket",
        "rasi",
        "regex",
        "rust",
        "scheme",
        "toml",
        "vim",
        "yaml",
        "zig",
    },
    sync_install = false,
    auto_install = false,
    ignore_install = {},
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = { "org" },
    },
}
