#!/usr/bin/env bash

sxhkd &
#xkbcomp ~/dhm.xkb $DISPLAY &
polybar right &
polybar left &
xinput set-prop 'Logitech Gaming Mouse G502' 292 1

bspc monitor DP-0  -d 1 2 3 4 5

bspc config border_width         1
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc desktop --focus 1
