* TODOs
** General [0/12]
- [ ] embark?
- [ ] marginalia?
- [ ] mu4e/notmuch
- [ ] dired+
- [ ] lsp
- [ ] ripgrep
- [ ] magit-todos
- [ ] pass
- [ ] doom-modeline?
- [ ] windows/avy?
- [ ] format on save
- [ ] delayed init with new emacs version?
- [ ] snippets, for instance for org src blocks

** Languages [0/4]
- [ ] more org
- [ ] haskell
- [ ] data formats (json, yaml, csv, ...)
- [ ] markdown

* Config
Put customizations code into a separate file. We do not want to append
it to our =init.el=.

#+BEGIN_SRC emacs-lisp
(setq custom-file (concat user-emacs-directory "custom.el"))
(load custom-file 'no-error)
#+END_SRC

Disable the graphical GUI things like the menu bar and others.

#+BEGIN_SRC emacs-lisp
(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(tooltip-mode -1)
#+END_SRC

We want point to be inside newly opening help windows so may quickly close them with =q=.

#+BEGIN_SRC emacs-lisp
(setq help-window-select t)
#+END_SRC

Use the great [[https://protesilaos.com/modus-themes/][Modus Vivendi theme by Protesilaos Stavrou]].

#+BEGIN_SRC emacs-lisp
(load-theme 'modus-vivendi t)
#+END_SRC

Answering a question with =yes= instead of just =y= is just annoying.

#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

The [[https://github.com/noctuid/general.el][general]] package allows us to easily define keybindings. In
=evil-mode= we are using =SPC= as leader key, and =SPC m= as local
leader.

#+BEGIN_SRC emacs-lisp
;; Use general to define keymaps.
(use-package general)

;; Use SPC as leader key, like in Doom and neovim.
(general-create-definer my-leader-def
  :prefix "SPC")

;; Might use something else like , later, but SPC m should
;; suffice for now.
(general-create-definer my-local-leader-def
  :prefix "SPC m")
#+END_SRC

#+BEGIN_SRC emacs-lisp
(my-leader-def
  :keymaps '(normal visual)
  ;; SPC SPC as M-x alias
  "SPC" 'execute-extended-command
  ;; Buffer commands
  "b b" 'ibuffer
  "b q" 'kill-this-buffer)

(use-package evil
  :config
  (evil-mode 1)
  :init
  (setq evil-want-integration t)
  (setq evil-want-keybinding nil)
  (general-define-key
   :states 'normal
   :keymap 'evil-window-map
   ;; Normal mode keybindings for evil commands
   "C-w C-h" 'evil-window-left
   "C-w C-j" 'evil-window-down
   "C-w C-k" 'evil-window-up
   "C-w C-l" 'evil-window-right
   "C-w d" 'evil-window-delete
   "C-w C-d" 'evil-window-delete))

(use-package evil-collection
  :after evil
  :config
  ;; Register all bindings in evil-collection
  ;(evil-collection-init 'apropos) ;; TODO
  ;(evil-collection-init 'cider) ;; TODO
  ;(evil-collection-init 'company) ;; TODO check
  (evil-collection-init 'dired) ;; TODO check
  ;(evil-collection-init 'dired-sidebar) ;; TODO check
  ;(evil-collection-init 'ediff) ;; TODO
  (evil-collection-init 'elisp-mode)
  ;(evil-collection-init 'flycheck) ;; TODO
  (evil-collection-init 'ibuffer) ;; TODO
  (evil-collection-init 'magit)
  ;(evil-collection-init 'magit-todos) ;; TODO
  ;(evil-collection-init 'pass)
  ;(evil-collection-init 'ripgrep)
  (evil-collection-init 'which-key) ;; TODO
  )

(use-package evil-surround
  :config
  (global-evil-surround-mode))

(use-package projectile
  :config
  (projectile-mode +1)
  (my-leader-def
    :keymaps '(normal visual)
    "p f" 'projectile-find-file
    "p k" 'projectile-kill-buffers
    "p p" 'projectile-switch-project))

(use-package magit
  :config
  (my-leader-def
    :keymaps '(normal visual)
    ;; TODO learn about magit-dispatch
    "g g" 'magit-status))

(use-package nix-mode
  :mode "\\.nix\\'")

(use-package selectrum
  :config
  (selectrum-mode +1))

(use-package smartparens
  :config
  (smartparens-global-mode 1))

(use-package orderless
  ;; TODO customize?
  :custom (completion-styles '(orderless)))

(use-package company
  :init
  (add-hook 'after-init-hook 'global-company-mode))

(use-package hl-todo
  :init
  (add-hook 'after-init-hook 'global-hl-todo-mode))

;; TODO is this necessary? configure?
(use-package switch-window)

(use-package which-key
  :init
  (add-hook 'after-init-hook 'which-key-mode))
#+END_SRC
